main: com.technoguyfication.discordlink.DiscordLink
name: DiscordLink
version: ${version}
api-version: "1.15"
description: ${descrption}
load: POSTWORLD
author: ${author}
website: ${url}
depend: [Vault]
commands:
  discordlink:
    description: An example command
    permission: discordlink.info
    usage: /discordlink
permissions:
  discordlink.*:
    description: DiscordLink
    default: op
    children:
      test.info: true
